services:
  frontend:
    build:
      context: ./font  
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./font:/app  
      - /app/node_modules  
    environment:
      - CHOKIDAR_USEPOLLING=true  

  backend:
    build:
      context: ./back 
      dockerfile: Dockerfile
    ports:
      - "2909:2909"
    # restart: always
    # volumes:
    #   - ./back:/app
    # working_dir: /app
    # command: air
