name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_URL }}

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t my-app-backend ./back
          docker tag my-app-backend:latest ${{ secrets.ECR_URL }}/my-app-backend:latest
          docker push ${{ secrets.ECR_URL }}/my-app-backend:latest

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t my-app-frontend ./font
          docker tag my-app-frontend:latest ${{ secrets.ECR_URL }}/my-app-frontend:latest
          docker push ${{ secrets.ECR_URL }}/my-app-frontend:latest

      - name: Deploy to Amazon ECS
        run: |
          aws ecs update-service --cluster my-cluster --service backend-service --force-new-deployment
          aws ecs update-service --cluster my-cluster --service frontend-service --force-new-deployment
